name: env_casanntra
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.11
  - pip
  - ipykernel
  - jupyter_bokeh
  # add dependencies from setup.py here
  # - pandas # ...
  # dev dependencies
  # - pytest
  # - pytest-cov
  # - black
  # setup development environment by 
  # conda activate env_casanntra
  # pip install -e .

